Ansible 2
Otus-DevOps-2018-05/sergeykudelin_infra pull request #10
Opened 2018-07-19 13:26 UTC by sergeykudelin

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Пересобраны образы в packer с использование playbook-ов
 - Созданые playbook-и
 - Добавлена динамическая инвентаризация с помощью gce.py

## Как запустить проект:
 - ansible-playbook site.yml

## Как проверить работоспособность:

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-07-24 11:31 UTC, Avtandilko requested changes
Сергей, билд тревиса красный.

2018-07-24 11:44 UTC, sergeykudelin commented
Исправил.

2018-07-24 14:53 UTC, Avtandilko approved these changes

2018-07-24 14:55 UTC, Avtandilko commented
Сергей, задание сделано отлично 👍

Единственное - просьба настроить git на всех своих устройствах, сейчас как будто 4 разных человека коммитят.

2018-07-25 09:43 UTC, sergeykudelin commented
Спасибо, за замечание, такое происходит из-за того что юзается локальный сервер git, и когда есть необходимость склонить репу с нуля, то забываю прописать нужного пользователя для конкретной репы, а множественные варианты, это был перебор какой именно name использует github. Сейчас поставил на поток данное действие, постараюсь не забывать.

2018-07-25 09:57 UTC, merged