Ansible 4
Otus-DevOps-2018-05/sergeykudelin_infra pull request #12
Opened 2018-07-25 10:36 UTC by sergeykudelin

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
* Локальная разработка при помощи Vagrant - в Vagrantfile описаны конфигурации appserver, dbserver
* Добавлен плейбук base.yml для ansible bootstrap на хостах, где не установлен python
* Доработана роль db для использования в Vagrant, в которую добавлены таски config_mongo.yml, install_mongo.yml
* В Vagrantfile добавлены ansible провижинеры для appserver и dbserver
* Добавлены тесты роли db через molecula и testinfra

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-07-25 10:37 UTC, sergeykudelin commented
Касательно не корректно настроеного пользователя репозитория, такое происходит из-за того что юзается локальный сервер git, и когда есть необходимость склонить репу с нуля, то забываю прописать нужного пользователя для конкретной репы, а множественные варианты, это был перебор какой именно name использует github. Сейчас поставил на поток данное действие, постараюсь не забывать.

2018-08-06 08:22 UTC, whitew1nd requested changes
Looks good to me, в том, что касается задания 👍 
Github пока еще показывает, что требуется починить конфликты, нужно починить

2018-08-06 16:21 UTC, sergeykudelin commented
Исправил конфликты и замечание которые появились при прохождении тестов в Travis-CI

2018-08-07 07:51 UTC, whitew1nd approved these changes

2018-08-07 08:26 UTC, merged